Model.md

Remove excess line from Model.md

---

README.md
enforcer.go
management_api.go
model/assertion.go
model/policy.go
model_test.go
rbac/default_role_manager.go
rbac/default_role_manager_test.go
rbac/role_manager.go

Define RoleManager as interface, and rename existing RoleManager struct
to defaultRoleManager to provide a default implementation and backwards
compatability.
Defines RoleManagerConstructor to allow specifying a function for
creating a new RoleManager.
Adds SetRoleManagerConstructor method to Model to allow setting the
function to call for a new instance of RoleManager.
Adds implementation of RoleManagerConstructor to Model that will create
an instance of the defaultRoleManager just like before.
Updates Assertion to reference RoleManager interface instead of an
instance. Updates Assertions.buildRoleLinks() to use newRoleManagerFunc
that holds the RoleManagerConstructor.
All test are passing with the only change being *RoleManager to
RoleManager.
Resolves #36

Feature: Define RoleManager as interface

---

management_api.go

Expand the Management API to include functions allowing for multiple policy definitions to be managed concurrently, for example grouping policies "g" and "g2" in the case of RBAC with resource roles enabled. Preexisting functionality is unchanged.
The primary use case I'm interested in is support for resource roles, as in the example above, but this change will allow for more flexible usage of the API in general, to more closely mirror what is possible for static policies. My goal is to minimize disruption and fit into the existing API as cleanly as possible.
Example:
```golang
enforcer.AddGroupingPolicy("user", "admin")  // unchanged
enforcer.AddNamedGroupingPolicy("g2", "data1", "data_role") // new capability
```

[feature] Enable multiple policies/roles in API

---

enforcer_safe.go
enforcer_test.go
error_test.go
examples/keymatch_custom_model.conf
examples/priority_policy_indetermine.csv
examples/rbac_model_with_not_deny.conf
file-adapter/adapter_mock.go
management_api_test.go
model/model_test.go
model_test.go
persist/persist_test.go

Hi Yang,
Here's a PR to improve your code coverage from 76% to 99% (I could probably get the last little bit with some refactoring). Not sure how Coveralls is calculating coverage - I'm using go test -coverprofile=coverage.out github.com/casbin/casbin)
I mostly tried to add new test cases but some functionality wasn't testable without minor code changes.
--Added safe methods for AddPolicySafe/RemovePolicySafe/RemoveFilteredPolicySafe
--Simplified the recover blocks for enforcer_safe (I saw that you got your code from Stack Overflow but that answer in my mind is overly complicated and untestable). I used the same approach I've seen in other projects like gin-gonic https://github.com/gin-gonic/gin/blob/master/recovery.go#L37.
--Added a mock file adapter
Also the sync enforcer is hard to …

Improve test coverage from 76% to 99%

---

rbac/default-role-manager/role_manager.go

Default role manager used a map which isn't thread safe. This caused `fatal error: concurrent map writes` when two goroutines tried to write to map.
I replaced map with `sync.Map` which is thread safe.

Fix default role manager concurrency

---

README.md

I noticed the Auth0 link was going to the wrong website - here's a quick fix for that 😄

Fix the Auth0 link in README.md

---

model_test.go
util/builtin_operators.go

(T)(v) is identical to T(v) when T is not a pointer type.
Found using https://go-critic.github.io/overview#typeUnparen-ref

remove redundant parenthesis from type conversion exprs

---

management_api_test.go

Fix test title typo from 'Objeccts' to 'Objects'

---

enforcer.go
filter_test.go

Do not load the full policy when initializing a filtered adapter.
Closes #96

[enhancement/#96] Skip filtered policy init

---

enforcer.go

```
runtime error: index out of range
/usr/local/go/src/runtime/panic.go:513 (0x42a5a8)
/usr/local/go/src/runtime/panic.go:44 (0x4293e9)
/go/pkg/mod/github.com/casbin/casbin@v1.8.0/enforcer.go:339 (0x9d153a)
/go/pkg/mod/github.com/casbin/casbin@v1.8.0/enforcer_synced.go:106 (0x9d24e3)
```
We had this error in production. 
The code gives more info on the error when it occurs

Add more explicit panic log when the defined policy rule is invalid

---

persist/adapter.go

Signed-off-by: Steve <persistence2013@sina.com>
As the [golang wiki](https://github.com/golang/go/wiki/Range#gotchas) said
>the value property of range (stored here as item) is a copy of the value from items
So if we want to modify the value of `Slice`,  the for loop is more suitable in my mind.

make code more elegant and efficient

---

.gitignore
errors/rbac_errors.go
examples/rbac_policy.csv
examples/rbac_with_domains_policy.csv
rbac/default-role-manager/role_manager.go
rbac_api.go
rbac_api_synced.go
rbac_api_test.go

* An issue referenced [here](https://github.com/casbin/casbin/issues/236#issue-451381779) stated that rbac_api.go does not return errors. This is not ideal.
* vendor wasnt in `.gitignore`

Added errors in rbac_api.go

---

enforcer.go

While doing some profiling of our casbin enforcement model I discovered a significant time spent in copying memory around to create the govaluate parameter map.
Excerpt of profile in `Enforce` function:
```
10ms       20ms    337:                   if len(e.model["p"]["p"].Tokens) != len(pvals) {
.          .    338:                           panic(
.          .    339:                                   fmt.Sprintf(
.          .    340:                                           "Invalid Policy Rule size: expected %d got %d pvals: %v",
.          .    341:                                           len(e.model["p"]["p"].Tokens),
.          .    342:                                           len(pvals),
.          .    343:                                           pvals))
.          . …
```

Performance improvement: avoid copying govaluate parameters unnecessarily

---

management_api.go
util/builtin_operators.go
util/util.go

- Ensure policy param args are not zero before attempting to address slice values. 
- Run Go fmt on source

Handle zero length policy params in the enforcer code

---

enforcer.go
enforcer_cached.go
rbac/default-role-manager/role_manager.go

This code shows a big performance issue when inserting many policies in
a row. This is because it builds a string to log without checking for a
logger (thus can build a string without using it).
Also concatening string in a loop cause a lot a memory allocation that
has to be handled by the garbage collector, which is the real
performance hit.
Using a string.Builder avoid this issue. Also check if the logger is
enabled before doing anything.
Change-Id: Ibb63237d6065e1d1a77bb290a493bf8715b150e3
Signed-off-by: Loïc Collignon <loic.collignon@iot.bzh>

Test for a logger and use string.Builder

---

enforcer_synced.go

some methods in management_api are missing in SyncedEnforcer
those methods can fail when called while loading.
this PR adds those methods.

add missing methods in management_api to SyncedEnforcer

---

enforcer.go

Added getter for role manager. It was necessary to have a getter so as to use `AddMatchingFunc` method on the RoleManager struct.

added getter for RoleManager

---

enforcer.go

According to this [official blog](https://blog.golang.org/godoc-documenting-go-code) one of the formatting rules for Godoc is
> Pre-formatted text must be indented relative to the surrounding comment text
This PR makes the code formatted properly in Godoc. I've skimmed through the doc and find this is the only part that need fixing. Please do let me know if I miss something. Thanks!
Here is a screenshot on Godoc that shows how it will look after the fix:

Properly indent sample code in doc

---

config/config.go
model/model.go
model/model_test.go

For #333 this PR checks for the existence of r,p,e and m model sections, returning an error when loading if any of those is not present and indicates which required sections are missing.
This also has a minor typo correction in a comment and a move of the empty string check in model.AddDef().

LoadPolicyLine Required Section Check

---

enforcer.go

If a policy is not correctly defined, then throw an error instead of a panic:
https://github.com/casbin/casbin/issues/312

Handle panic in enforce

---

config/config.go
config/config_test.go
config/testdata/testini.ini

- The actual code strips the multiline char but sometimes
it leads to syntax errors because not compatible chars may
result appended.

Fix syntax errors on multiline config sentences

---

enforcer_synced.go
enforcer_synced_test.go

Goroutine which is handling auto load policy is immediately exited after user requested to stop it, instead of sleeping.
After I commited, I realized maybe one issue?
StopAutoLoadPolicy will be blocking operation if there is no running auto load, can be solved again adding bool flag. But why user would want stop auto load policy if he didn't start it before.

Go idomatic stopping goroutine for auto load policy

---

rbac_api.go
rbac_api_test.go

Previously it just removed Grouping policies. Now it shares same implementation as DeleteRole
casbin/node-casbin#118

fix(rbac_api.go): DeleteUser should remove Policies + Grouping Policies

---

enforcer_synced.go

The `LoadFilteredPolicy` method was missing on Synced adapter.

Add synced version of LoadFilteredPolicy.

---

util/builtin_operators.go

golint warning:
> should replace errors.New(fmt.Sprintf(...)) with fmt.Errorf(...)
I think the new is more concise than the old

Use fmt.Errorf() replace errors.New(fmt.Sprintf())

---

examples/basic_model_without_spaces.conf
model/model.go
model_test.go

As saw in issue #412, the users are facing problems parsing ```CONF``` files. So, why don't we extend our support to just comma(no space) separated values ```,``` , not just ```, ```.
In this way, users will be able to write CONF files in both the above ways.

Added support for the CONF files having just comma (no spaces) separated values.

---

.github/workflows/default.yml
.releaserc.json

The following is supported via GitHub actions: 
- test casbin is working on golang 1.11, 1.12, 1.13, 1.14
- add automate package to Release(#444)

ci: add GitHub actions

---

effect/default_effector.go
effect/effector.go
enforcer.go
enforcer_interface.go
enforcer_test.go
management_api_test.go
util/util.go

For #355
Explain why an enforcement was or wasn't satisfied.Controlled by `autoExplain` in enforce,Print the policy related to the result to the log.
such as `some(where (p.eft == allow))`, the explanation will be all allowed policy.
whether it hits depends on user selected effect. User can modify it by interface EffectorEx

Explain enforcement in log

---

util/builtin_operators.go
util/builtin_operators_test.go

fix: #447, improve KeyMatch method to avoid endless loop.

fix: improve KeyMatch method to avoid endless loop

---

enforcer_synced.go

Use "github.com/casbin/casbin/v2/log" instead of "log" package.
It will increase usability -- I need to use the zap logger, but synced logger prints to default logger at the same time as the std log, which can cause a race condition.

fix(synced enforcer): use casbin logger

---

enforcer_cached_b_test.go
model_b_test.go

fix: #465
And the rest of the logs are generated by unit tests

fix: Disable logger in benchmark

---

enforcer_synced.go

Use read lock in `Enforce()` method instead of write lock in synced enforcer.  
Write lock blocks other readers and writers, while read lock do not block other readers. So calling `SyncedEnforcer.Enforce()` can be a performance bottleneck when using `SyncedEnforcer` as singleton, for example.
Previously the read lock was in this method, and in [this PR](https://github.com/casbin/casbin/pull/310) it was changed to write lock due to error related to concurrent map writes. But the error was caused by bug in nested `Enforcer` instance, not synced enforcer. And this bug has been already fixed [here](https://github.com/casbin/casbin/issues/323).  
So we can use read lock again.

perf: Use read lock in synced enforcer

---

internal_api.go
model/assertion.go
model/policy.go

There is no need to record ```effects``` in ```AddPolicies``` and ```RemovePolicies``` as we know that the operations are atomic, so either all rules are successful or none.

fix: Necessary code changes in buildIncrementalRoleLinks.

---

error_test.go
internal_api.go
model/policy.go

Should resolve #415.
> If the model changes are made first but the adapter fails (network, code error, anything really), the in-memory model and adapter store will be out of sync. The next time the adapter is instantiated it will call LoadPolicy(x) in the store and the changes made in-memory will obviously be lost.
This change moves the adapter action to be first. The mutation of in-memory state is done only if the store does not error (not implemented should be fine still).

fix: Perform adapter persist actions before model changes

---

errors/rbac_errors.go
examples/rbac_with_all_pattern_model.conf
examples/rbac_with_all_pattern_policy.csv
examples/rbac_with_domain_pattern_model.conf
examples/rbac_with_domain_pattern_policy.csv
model_test.go
rbac/default-role-manager/role_manager.go
rbac/default-role-manager/role_manager_test.go
rbac_api_test.go

This commit not only supports pattern function in 3rd args of g, but also can be used in policy, such as
```
p, data1_admin, *, data1, read
p, data1_admin, *, data1, write
g, alice, data1_admin, domain1
```

feat: Support pattern function in 3rd args of g

---

.github/workflows/default.yml
config/config.go
enforcer.go
enforcer_synced.go
enforcer_synced_test.go
log/default_logger.go
management_api.go
model/assertion.go
model/function.go
model/policy.go
persist/adapter.go

This PR remove extra/unnecessary child locks. thread-safety will be guaranteed by top-level lock. It helps passing `go test -race`

fix: remove unnecessary locks

---

enforcer_synced.go

add AddGroupingPolicies, AddNamedGroupingPolicies, AddPolicies & AddNamedPolicies to SyncedEnforcer
btw. it can be pretty confusing to used the `SyncedEnforcer` assuming all functions are synced.
https://github.com/casbin/casbin/blob/7841fd31a667614446024033dc03185dbd793a88/enforcer_interface.go#L25-L27
this won't fail since
https://github.com/casbin/casbin/blob/7841fd31a667614446024033dc03185dbd793a88/enforcer_synced.go#L28-L33
i would suggest to wrap every single function instead and keep the enforcer private
```go
type SyncedEnforcer struct {
e               *Enforcer
m               sync.RWMutex
stopAutoLoad    chan struct{}
autoLoadRunning int32
}
```

add missing functions to SyncedEnforcer

---

errors/rbac_errors.go
internal_api.go
model/policy.go

fix: add checks fieldValues to remove filtered policy

---

enforcer.go
examples/abac_with_rbac.conf
examples/abac_with_rbac.csv
model_test.go

fix: compatible RBAC in ABAC

---

enforcer.go
enforcer_test.go
error_test.go

When there is no policy found:
1. Provide better error message when using eval() in matcher.
2. It is unnecessary to throw a null pointer error when use EnforceEx function, "explainIndex" is return by interface, should check this value, make sure that this value does not break the rest of the logic.

fix: update enforcer logic when there is no policy found

---

enforcer.go
enforcer_interface.go
internal/internal.go
internal_api.go
model/policy.go

Now the return value of internal_api is too much, this function need to processe include model, adapter, dispatcher, watcher and logger. I think this function should be simplified.
When the dispatcher updates the policy, it needs to update model and adapter one by one and call `BuildIncrementalRoleLinks()`, which makes the development of the plug-in more complicated, so I separated the main component model and adapter as a new api that can be called from outside.

fix: Separate internal_api

---

enforcer.go
enforcer_synced.go
log/default_logger.go
model/assertion.go
model/model.go
model/policy.go
model_test.go
rbac/default-role-manager/role_manager.go
rbac/role_manager.go

- Fix print stdout log without control.
- Change global logger to enforcer. Every enforcer as well as its role manager and model could use its own logger.
- Fix: https://github.com/casbin/casbin/issues/629

feat: change global logger to enforcer

---

enforcer_synced.go

The SyncedEnforcer is used on the condition of concurrency, so a lock is needed for preventing data race. We use a read-write lock for better performance. Cause LoadModel is the read action, so I called m.Lock() instead of RLock(), after read operation, release the lock. Model is used to parse the policy, so it is nessessary to call LoadPolicy after LoadModel.
Fix: https://github.com/casbin/casbin/issues/639

fix: LoadModel concurrency

---

management_api.go

AddNamePolicy uses the slice param passed in, when the param changing, and the policy will change too
Fix: https://github.com/casbin/casbin/issues/663

fix: slice reference in AddNamePolicy

---

README.md

This updates the installation path to v2, and adds "GO111MODULE=on" to enable use of go modules by default.

docs: update import path in README.md to v2

---

enforcer_synced.go
rbac_api_synced.go

This PR "re-synced" the synced enforcer... Basically:
- add the missing functions to the synced enforcer (there was quite a lot)
- move the functions that belong to the RBAC API into `rbac_api_synced.go`
- re-order some functions in `enforcer_synced.go` to match the `enforcer.go` order (to make it easy to find the missing functions).

fix: add missing functions to the synced enforcer

---

rbac/default-role-manager/role_manager.go
rbac/default-role-manager/role_manager_test.go

This branch fixes casbin/casbin#735
The problem in the code was that the `defaultrolemanager.NewRoleManager` constructor method signature defines a `rbac.RoleManager` instead of a `*RoleManager`.
As side effect, this also involved the import of `rbac`, which is of no use in the `defaultrolemanager` package.
The important aspect to take care of, in fact, is that `defaultrolemanager.RoleManager` adheres to the `rbac.RoleManager`.
This is granted by the language itself.
This modification allows to avoid the type casting.

fix: Unable to add domain matching func

---

examples/rbac_with_domains_policy2.csv
model_test.go
rbac/default-role-manager/role_manager.go
rbac/role_manager.go
rbac_api.go
rbac_api_with_domains_test.go

Fix: https://github.com/casbin/casbin/issues/744

feat: Add GetDomainsForUser() API

---

frontend.go

If you call CasbinJsGetPermissionForUser more than once, the policies are corrupted. Each run duplicate ptype. That is, after the second launch, the policy looks like this:
```
p, p, alice, data1, read
```

fix: duplicate policy type when calling CasbinJsGetPermissionForUser

---

enforcer_synced.go

fix: implement EnforceWithMatcher, EnforceEx, EnforceExWithMatcher

---

enforcer_synced.go

Pass variadic as slice by mistake.

fix: should use rvals... to avoid pass []interface{}

---

internal_api.go
persist/watcher_ex.go
watcher_ex_test.go

Fix: https://github.com/casbin/casbin/issues/775
As I mentioned in the issue
https://github.com/casbin/casbin/issues/775
we'd like to have `ptype` parameter in WatcherEx methods. 
This pr is a proposal, and aparently this will break exiting WatcherEx implementation though...

feat: add `ptype` parameter for WatcherEx methods

---

internal_api.go
rbac_api_with_domains.go
rbac_api_with_domains_test.go

fix: bug of GetAllUsersByDomain

---

rbac_api.go
rbac_api_test.go

feat: add method GetImplicitResourcesForUser

---

frontend_old.go
frontend_old_test.go

Fix: https://github.com/casbin/casbin/issues/774

fix: Add back CasbinJsGetPermissionForUserOld(), which is removed in: https://github.com/casbin/casbin/commit/3ab5e9ac41ee0448b76594c39363732e839c8f7f

---

log/mocks/mock_logger.go
model/model.go
model/model_test.go

fix: matcher function lost

---

README.md

quickfix over syntax error on the readme file

fix: syntax error on example within readme.md

---

examples/performance/rbac_with_pattern_large_scale_model.conf
examples/performance/rbac_with_pattern_large_scale_policy.csv
model_b_test.go
rbac/default-role-manager/role_manager.go
role_manager_b_test.go
util/builtin_operators.go

fix: #781 and fix: #829
```
goos: windows
goarch: amd64
pkg: github.com/casbin/casbin/v2
cpu: Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz
```
|Name       |N        |Time            |
| -------------|:--------------:|--------------:|
| BenchmarkBuildRoleLinksWithPatternLarge-16  (Now)  | 1 | 1380663800 ns/op |
| BenchmarkBuildRoleLinksWithPatternLarge-16  | 1 | 16264016400 ns/op |
| | | |
| BenchmarkBuildRoleLinksWithDomainPatternLarge-16 (Now) | 193 | 6605217 ns/op | 
| BenchmarkBuildRoleLinksWithDomainPatternLarge-16 | 6 | 195383033 ns/op | 
| | | |
| BenchmarkBuildRoleLinksWithPatternAndDomainPatternLarge-16 (Now) | 1| 1828370400 ns/op | 
| BenchmarkBuildRoleLinksWithPatternAndDomainPatternLarge-16 | 1 | 62452898100 ns/op | 
| | | |
| BenchmarkHasLinkWithPatternLarge-16  (Now) | 1120 | …

fix: improve AddLink and HasLink with KeyMatch4 pattern performance

---

rbac/default-role-manager/role_manager.go

Fix: https://github.com/casbin/casbin/issues/860
Should continue instead of returning an error in `GetUsers` function refering the `GetRoles` function:
https://github.com/casbin/casbin/blob/master/rbac/default-role-manager/role_manager.go#L264

fix: get users of role issue

---

model/function.go
util/builtin_operators.go
util/builtin_operators_test.go

Fix: https://github.com/casbin/casbin/issues/909
Add KeyMatch5 to ignoring params in URL when matching keys.
Related Issue: #909 
Add a new operation `keyMatch5`
Unit test
Has exported function/method change

feat: keyMatch5 for ignoring params in url

---

enforcer.go
examples/abac_not_using_policy_model.conf
examples/abac_rule_effect_policy.csv
model_test.go

Signed-off-by: abingcbc <abingcbc626@gmail.com>
Fix: https://github.com/casbin/casbin/issues/917
Ignore all policies when matcher doesn't contain any match related to policy.

fix: abac not using policy

---

enforcer.go
enforcer_test.go
examples/eval_operator_model.conf
examples/eval_operator_policy.csv

Fix: https://github.com/casbin/casbin/issues/939

fix: priority of eval operator

---

model_b_test.go
util/builtin_operators.go

Previously, the G-function cache used repeated fmt.Sprintf("%v", x) and string concatenation to generate its cache key. This resulted in lots of unnecessary allocations, both in the process of Sprintf and in an O(n²) string building loop. This change allocates everything in one go and relies on the fact that we already know everything is strings.

perf: Reduce allocations and printfs in G-function cache.

---

.github/workflows/default.yml

Only the last two major versions of Go are supported, so the test
runners should be brought up to date. This keeps `1.14` so we maintain
overlap with the previous configuration.
https://go.dev/doc/devel/release#policy

test: Update test runners to recent versions of Go.

---

.github/workflows/default.yml

fix: https://github.com/casbin/casbin/pull/942#issuecomment-1085848855
Upgrade to v3 as suggested by a member of [golangci/golangci-lint-action](https://github.com/golangci/golangci-lint-action): https://github.com/golangci/golangci-lint-action/issues/434#issuecomment-1086174860

ci: upgrade golangci-lint-action to v3

---

enforcer.go

I've run into a couple of nil pointer exceptions that would have benefited from a stack reference. This simple adds the stack trace to the recovery error.

feat: Log panic stack

---

util/util.go
util/util_test.go

Similar for Java: https://github.com/casbin/jcasbin/pull/268

fix: EscapeAssertion should escapes "r[0-9]." instead "r"

---

examples/rbac_with_multiple_policy_model.conf
examples/rbac_with_multiple_policy_policy.csv
rbac_api.go
rbac_api_synced.go
rbac_api_test.go

synced a new feature from pycasbin
see at  [pycasbin: add named policy](https://github.com/casbin/pycasbin/pull/256)

feat: allow permissions management to use additional p-types

---

enforcer.go
enforcer_synced.go

As mentioned [here](https://github.com/casbin/redis-watcher/issues/26#issuecomment-1111698719), the `SetWatcher` needs to keep WatcherEx's customized callback.
This is a part of fixing for https://github.com/casbin/casbin/issues/999.
A flaw: There's no way to check whether the callback is set due to the limitation of the `WatcherEx ` interface.

feat: Enforcer.SetWatcher supports WatcherEx's customized callback.

---

enforcer.go
model_b_test.go

Fix: https://github.com/casbin/casbin/issues/1000
Benchmark results:
```
Before:
BenchmarkABACRuleModel-12    	      49	  21753411 ns/op	 4408055 B/op	  100021 allocs/op
After:
BenchmarkABACRuleModel-12    	     165	   7101567 ns/op	 1320970 B/op	   40087 allocs/op
```
Signed-off-by: Andreas Bichinger <andreas.bichinger@gmail.com>

perf: add eval to function map

---

enforcer.go
enforcer_synced.go

Reverts casbin/casbin#988
This change can cause races when the management api is used while a new model is being prepared.
Situation:
* T1: Routine 1: loads new model from db into `newModel`
* T2: Routine 2: write change against db and current model
* T3: Routine 1: replace `model` with `newModel`
In this case the write in T2 would not be present until the next reload.
Sadly that brings back the issue that slow policy loading stalls any enforcements. One option might be to use a different lock for such performance critical operation and accept a certain degree of eventual consistency.

fix: revert lock less when syncing

---

constant/constants.go
effector/default_effector.go
internal_api.go
model/assertion.go
model/model.go
model/model_test.go
model/policy.go
rbac_api.go
rbac_api_with_domains.go

Some APIs (mostly RBAC APIs) need to obtain the index of variables such as sub, obj, dom, priority, etc. in policy_define. So this PR did the following work
1. add ``FieldIndexMap`` to store index.
2. add ``GetFieldIndex`` and ``SetFieldIndex``, try to get the index with ``sub, obj, dom, priority`` as the default definition named values. If the user does not use the default value, then ``SetFieldIndex`` should be used to set the index
Some other work is adding constants, putting some constants together instead of using strings directly in the code.
related: https://github.com/casbin/casbin/issues/1015#issuecomment-1166218883 #1015 

feat: add FieldIndexMap and constant

---

model/model.go
model/policy.go
persist/adapter.go

Fixes: #1016 
Next, we may replace the existing `HasPolicy` call with this and remove check at `Enforce` func.

feat: add HasPolicyEx() API to determine the policy exist with an error 

---

examples/rbac_with_domain_pattern_policy.csv
rbac/default-role-manager/role_manager.go
rbac_api.go
rbac_api_test.go

fix: https://github.com/casbin/casbin/issues/969
`GetImplicitPermissionsForUser` depends on `GetFilteredPolicies` to query permissions. But when `enforcer` gets filtered policies, it doesn't support domain matching.
So there are main changes in this PR:
1. Make `match` of role manager public and reuse this function for domain matching when getting policies.
2. Add a new function `GetFilteredPolicyWithDomainMatching` for the user requirements mentioned in
https://github.com/casbin/casbin/issues/969.
4. Unit tests.

feat: support domain matching when getting permissions

---

model/function.go
util/builtin_operators.go
util/builtin_operators_test.go

We have `keyMatch3` for `/alice_data/{resource}` now while lacking the corresponded `keyGet` for it. 
A user case: https://github.com/casbin/casbin/issues/1048#issuecomment-1179533275
The document is WIP.

feat: add KeyGet3 for support parsing curly bracket

---

enforcer_synced.go

`SavePolicy()` should require the lock for RW.

fix: wrong type of locking

---

util/builtin_operators_test.go

Recorrect the name of the test function in builtin_operators_test.go

fix: recorrect the name of test function in builtin_operators_test

---

internal_api.go

fix: https://github.com/casbin/xorm-adapter/issues/49#issuecomment-1195207543

fix: crashing when len(oldRule) != len(newRule) in UpdateFilteredPolicies()

---

enforcer.go
enforcer_test.go

`SortPoliciesBySubjectHierarchy()` should be executed at `loadFilteredPolicy()` just like `LoadPolicy()`.

feat: fix sub hierarchy invalid in `loadFilteredPolicy`

---

enforcer.go
model_test.go
rbac/default-role-manager/role_manager.go
rbac/role_manager.go
rbac_api.go
rbac_api_test.go

Fix: https://github.com/casbin/casbin/issues/1107

feat: add the missing methods like Match(), AddMatchingFunc() and AddDomainMatchingFunc() to the role manager interface

---

enforcer_interface.go
enforcer_synced.go
enforcer_synced_test.go
internal_api.go
management_api.go
management_api_test.go

fix: https://github.com/casbin/casbin/issues/1194
Add the following methods for Enforcer and SyncEnforcer
```golang
AddPoliciesEx(rules [][]string) (bool, error)
AddNamedPoliciesEx(ptype string, rules [][]string) (bool, error)
AddGroupingPoliciesEx(rules [][]string) (bool, error)
AddNamedGroupingPoliciesEx(ptype string, rules [][]string) (bool, error)
SelfAddPoliciesEx(sec string, ptype string, rules [][]string) (bool, error) 
```
The difference between these methods and the methods without the Ex suffix is that if one of the rules already exists, they will continue to check the next rule instead of returning false directly

feat: Add methods such as AddPoliciesEx

---

enforcer_interface.go

Fix: https://github.com/casbin/casbin/issues/1206
Defined missing interfaces.

fix: add UpdateNamedGroupingPolicy() APIs to implement the IEnforcer interface

---

enforcer_cached_synced.go

Fix: https://github.com/casbin/casbin/issues/1222
fix: change enforcer_cached_synced.go AddPolicies() API in the SyncedEnforcer.RemovePolicies to AddPolicies

fix: fix AddPolicies()'s bug in SyncedCachedEnforcer

---

enforcer_cached_synced_test.go
persist/cache/cache_sync.go

In a highly concurrent situation, Clear can be called while a mutex is held, which can cause issues when trying to unlock the mutex.
Fixes #1228

feat: don't crash if Clear gets called while holding a lock

---

rbac/default-role-manager/role_manager.go

fix: https://github.com/casbin/casbin/issues/1236
```golang
package main
import (
"fmt"
"log"
"testing"
"github.com/casbin/casbin/v2"
)
var e1 *casbin.Enforcer
func init() {
e, err := casbin.NewEnforcer("examples/rbac_with_domains_model.conf", "examples/rbac_with_domains_policy.csv")
if err != nil {
panic(err)
}
pPolicies := make([][]string, 0)
for i := 0; i < 100; i++ {
pPolicies = append(pPolicies, []string{fmt.Sprintf("user_%d", i), fmt.Sprintf("data_%d", i/10), "read"})
}
_, err = e.AddPolicies(pPolicies)
if err != nil {
log.Fatal(err)
}
e1 = e
}
func BenchmarkRunNoneParallel(b *testing.B) {
b.ResetTimer()
for i := 0; i < b.N; i++ {
_, _ = e1.GetNamedImplicitPermissionsForUser("p", "alice", "domain1")
}
b.StopTimer()
}
// Match2
func BenchmarkRunNoneParallel2(b *testing.B) { …
```

feat: optimize enforce performance by deleting cache in Match

---

enforcer.go
enforcer_cached.go
enforcer_cached_b_test.go
examples/priority_model_enforce_context.conf
examples/priority_policy_enforce_context.csv

This PR contains a small change to the ``EnforceContext`` type to allow caching enforce requests that have `EnforceContext` as the first parameter. This is to allow the `CachedEnforcer`  and `SyncedCachedEnforcer`  to cache enforce requests with `EnforceContext` as the first parameter.
The `GetCacheKey` already supports generating cache keys for arbitrary types if they implement `CachableParam` so this PR updates the `EnforceContext` so that it becomes a `CachableParam`.
Results (without the changes in this PR):
```
BenchmarkCachedWithEnforceContext-12                              355526              3420 ns/op
````
Results (with the changes in this PR):
```
BenchmarkCachedWithEnforceContext-12                             3807160               284.1 ns/op
````

fix: add EnforceContext' GetCacheKey()

---

enforcer_interface.go

Add the following missing Domain RBAC API's to the IEnforcer interface:
- DeleteRolesForUserInDomain
- GetAllUsersByDomain
- DeleteAllUsersByDomain
- DeleteDomains
- GetAllDomains
- GetAllRolesByDomain

feat: update IEnforcer for missing domain methods

---

rbac_api.go

Fix: https://github.com/casbin/casbin/issues/1363
Delete grouping policies with index 0, when deleting a role, so that role is deleted completely

feat: delete grouping policies with index 0 as well in DeleteRole() API

---

persist/adapter_context.go

Relate #1349 
Require `Adapter` interface in `ContextAdapter` is meaningless and wierd.

feat: remove Adapter requirement in ContextAdapter

---

enforcer.go

Fix: https://github.com/casbin/casbin/issues/1386

feat: fix role manager cache error when LoadPolicy and Enforce calls are concurrent

---

enforcer_distributed.go
enforcer_interface.go
enforcer_synced.go
enforcer_synced_test.go
frontend.go
internal_api.go
management_api.go
management_api_test.go
model/model.go
model/policy.go
model_test.go
rbac_api.go
rbac_api_synced.go
rbac_api_test.go
rbac_api_with_domains.go
rbac_api_with_domains_test.go

Fix #1369 
This issue was paritially fixed by #1371, and this PR contains a fully fix.
- Add nil check on `model` before anywhere `model["g"]["g"]` may be accessed.
- **Public API changed**

feat: add error to some of the APIs

---

persist/adapter_filtered_context.go
persist/batch_adapter_context.go
persist/update_adapter_context.go

By adding `filtered`, `batch`, `update` interfaces, make the `ContextAdapter` have equivalent definitions to `Adapter`
Fix #1397

feat: add ContextFilteredAdapter, ContextBatchAdapter, ContextUpdatableAdapter interfaces

---

enforcer.go
enforcer_synced.go

- `LoadPolicyFast` was added in #1109
- `LoadPolicyFast` has duplicate logic with `LoadPolicy` and is outdated caused by logic changes in `LoadPolicy`
- This PR delete the duplicate logic and reduce the lock range in a different way
Fix #1332

feat: refactor `LoadPolicy`, delete `LoadPolicyFast`

---

constant/constants.go
management_api.go
management_api_test.go
model/policy.go

Fix: https://github.com/casbin/casbin/issues/1409
- add GetValuesForFieldInPolicyAllTypesByName function to adynamically get fieldIndex for each ptype
- add test for getting objects (subjects and actions are also included) in RBAC with domains mode
`GetAll{things}` and `GetAllNamed{things}` functions (things can be `actions`, `subjects`, `roles`) use hard-coded `fieldIndex` while fetching the corresponding resources, which causes incorrect behavior when the field indexes change.
According to [the documentation](https://casbin.org/docs/rbac-with-domains), the RBAC mode with domains have the convenient putting `domain` as the second param of a policy, while the `subject` is located at the second param (`fieldIndex=1`) in other mode.
> Note: Conventionally, the domain token name in policy …

feat: GetAllObjects has wrong result in RBAC with domains model

---

enforcer_cached.go
enforcer_cached_test.go

CachedEnforcer does not clean the result cached in memory when call ClearPolicy method

feat: CachedEnforcer does not clean the result cached in memory when call ClearPolicy method

---

model/model.go
util/builtin_operators.go

This PR minimizes the usage of `regexp.MustCompile` by precompiling the static ones and using a cache for dynamic ones.

feat: improve performance by pre-compiling regexes

---

internal_api.go

The `AddPolicy()` function's comment states that if the enforcer already contains the same policy as the one being added, `AddPolicy()` should `return false, nil`. However, the current implementation does not align with this behavior. This PR updates the code to ensure consistency with the function's intended behavior.

feat: fix addPolicyWithoutNotify()'s affected value

---

util/util.go

- Rewrote SortArray2D to support jagged (non-uniform) 2D string slices, avoiding out-of-range panics.
- Ensure shorter rows are prioritized when rows are otherwise equal

feat: improve SortArray2D() to support variable-length rows and prevent panics

---

rbac/default-role-manager/role_manager.go
rbac/default-role-manager/role_manager_test.go
role_manager_b_test.go

close #1318
Add `mutex `protection to `HasLink `operations in both `RoleManagerImpl `and `ConditionalRoleManager`

feat: prevent race condition in HasLink with temporary roles

---

model_test.go
rbac/default-role-manager/role_manager.go
rbac/role_manager.go
rbac_api_with_domains.go
rbac_api_with_domains_synced.go
rbac_api_with_domains_test.go

close #1492 
The original `DeleteDomains()` only performed the task of `DeleteAllUsersByDomain()`, but now `DeleteDomains() ` will delete all associated policies as well.

feat: completely remove domain from RoleManager when calling DeleteDomains

---

internal_api.go
model/assertion.go
model/model.go

Fixes [concurrent writes on assertion #1514](https://github.com/casbin/casbin/issues/1514)
The issue was caused by concurrent access to `FieldIndexMap` in the `Assertion` struct, which could lead to "concurrent map writes" panic when multiple goroutines simultaneously call `GetFieldIndex()`.
- `model/assertion.go`: Added mutex field and protected copy operation
- `model/model.go`: Added read/write lock protection in `GetFieldIndex`
- `internal_api.go`: Added write lock protection in `SetFieldIndex`
Closes #1514

feat: add mutex protection for FieldIndexMap to prevent concurrent writes
