persist/adapter.go
persist/file_adapter.go

Based on our gitter discussions, I modified the adapter to return error.

Return error from adapters

---

file-adapter/adapter.go
file-adapter/adapter_mock.go

Close opened files for reading

---

enforcer_test.go
examples/basic_policy_inverse.csv

Showing that getters/setters work correctly.

Tests to demo model/policy getters/setters.

---

enforcer.go
management_api.go

See issue https://github.com/casbin/casbin/issues/81

Remove reflect

---

enforcer_cached.go
enforcer_cached_b_test.go

1.add locker CachedEnforcer
2.check the interface convert
3.add benchmark cached file

fix CachedEnforcer panic

---

README.md
enforcer_test.go
examples/rbac_model_matcher_using_in_op.conf

Add test case TestMatcherUsingInOperator & examples/rbac_model_matcher & update README.md

Add test case TestMatcherUsingInOperator & examples/rbac_model_matcher & update README.md

---

enforcer.go

Found using https://go-critic.github.io/overview#typeSwitchVar-ref

use type switch var binding to reduce the amount of type assertions

---

model/policy.go

Found using https://go-critic.github.io/overview#commentedOutCode-ref

remove commented-out code

---

rbac_api_with_domains.go
rbac_api_with_domains_test.go

I implement ``GetUsersForRoleInDomain``, but the test is failed. I think the function: ``GetUsersForRole`` does not work. I don't know why, I am not familiar with casbin core, would you like finding this reason?

add GetUsersForRoleInDomain and test code

---

enforcer_safe.go
error_test.go

Add more safe functions and test code.

---

util/util.go
util/util_test.go

As already discussed here: #192

fix escapeAssertion bug

---

enforcer_cached.go
enforcer_cached_b_test.go

`sync.Map` appears to fit better here as the current implementation serializes any writes to the map even though they are typically writing separate keys (and typically only ever a given key, once). Using `sync.Map` reduces contention on this mutex.
From https://golang.org/pkg/sync/#Map
> The Map type is optimized for two common use cases: (1) when the entry for a given key is only ever written once but read many times, as in caches that only grow, or (2) when multiple goroutines read, write, and overwrite entries for disjoint sets of keys. In these two cases, use of a Map may significantly reduce lock contention compared to a Go map paired with a separate Mutex or RWMutex.
I think this use case fits the first well.
Running the added benchmark locally, I saw a roughly 40% improvement. …

Replace `sync.Mutex` with `sync.RWMutex` for CachedEnforcer 

---

watcher_test.go

Add Close() to SampleWatcher, fix: #253

---

enforcer.go
enforcer_cached.go
management_api.go

Deal with issues that golint reported

Minor change: Guard clauses

---

enforcer.go

Add EnforceWithMatcher method for https://github.com/casbin/casbin-server/issues/21

Add EnforceWithMatcher method

---

enforcer_synced.go

https://github.com/casbin/casbin/issues/309#issuecomment-542487705

fix the threading problem of the Enforce method of the SyncedEnforcer

---

enforcer_interface.go

* Used ifacemaker (https://github.com/vburenin/ifacemaker) to generate the interface automatically.
Issue: https://github.com/casbin/casbin/issues/318

Added Enforcer Interface to enable testing/mocking on client's end

---

CONTRIBUTING.md
README.md

A proposal for improving contributing to casbin docs.

Improve contributing documentation casbin/casbin#322

---

enforcer.go
internal_api.go

feat: controls whether to automatically notify Watcher

---

enforcer_interface.go
management_api.go

In IEforce, some methods are missing return value error

Fix wrong return types for methods in IEnforcer

---

util/builtin_operators.go
util/builtin_operators_test.go

Return errors in builtin function

---

examples/glob_model.conf
examples/glob_policy.csv
go.mod
model/function.go
model_test.go
util/builtin_operators.go
util/builtin_operators_test.go

Add a globMatch() built-in matching function

---

enforcer_interface.go

There were certain member function signatures missing in the enforcer interface. I have added those functions.

Missing member functions added to the interface.

---

.goreleaser.yml
.travis.yml

ci: integrated goreleaser

---

rbac_api_with_domains_synced.go

I have changed write locking-unlocking to read locking-unlocking as it is a getter function.

Made changes from normal locking-unlocking to read locking-unlocking for getters.

---

examples/rbac_with_pattern_policy.csv

Example bug fix.

---

rbac_api.go
rbac_api_test.go

Fix: https://github.com/casbin/casbin/issues/442

Fix GetImplicitUsersForPermission

---

enforcer.go
examples/abac_rule_model.conf
examples/abac_rule_policy.csv
model_test.go
util/util.go
util/util_test.go

Fix: https://github.com/casbin/casbin/issues/354

Scaling ABAC Rules

---

.github/semantic.yml

Always validate the PR title AND all the commits

chore: add semantic.yml

---

util/builtin_operators.go
util/builtin_operators_test.go

fix: improve KeyMatch method to avoid endless loop(#447).

fix: improve KeyMatch method to avoid endless loop

---

rbac_api.go
rbac_api_test.go

feat: add AddRolesForUser

---

config/config.go
config/config_test.go
config/testdata/testini.ini
examples/comment_model.conf
model_test.go

fix: support comment after effect and matcher

---

effect/default_effector.go
effect/default_effector_stream.go
effect/effector.go
effect/effector_stream.go
enforcer.go
enforcer_interface.go
enforcer_test.go
go.sum

fix: Quick return.

---

enforcer_interface.go
rbac_api_synced.go

Adds static check for Synced Enforcers and Cached
Fix SyncedEnforcer to correctly implement EnforcerInterface

fix: Add Static Check for Enforcer Implementations

---

util/builtin_operators.go

fix: add cache for g function

---

enforcer.go

Fix: https://github.com/casbin/casbin/issues/484

fix: an error occurs when run EnforceWithMatcher()

---

internal_api.go

Avoid typecast to BatchAdapter for RemovePolicy

Fix: Avoid typecast adapter to BatchAdapter for RemovePolicy

---

managerment_api_b_test.go
model/assertion.go
model/model.go
model/policy.go
persist/adapter.go

fix: use map to store policy index

---

enforcer_synced.go

sorry for the inconvenience.
did a copy & paste mistake

fix: wrong locks

---

log/default_logger.go
model/function.go
persist/adapter.go

Signed-off-by: Cheng JIANG <jiang.cheng@vip.163.com>
Try Fix: #518

fix: should remove escaped double quotes

---

rbac_api_with_domains.go
rbac_api_with_domains_synced.go
rbac_api_with_domains_test.go

fix: https://github.com/casbin/casbin/issues/522

fix: Add DeleteRolesForUserInDomain

---

README.md
enforcer.go
enforcer_interface.go
enforcer_synced.go
enforcer_test.go
error_test.go
filter_test.go
go.mod
internal_api.go
management_api_test.go
model/assertion.go
model/function.go
model/model.go
model/model_test.go
model/policy.go
model_test.go
persist/adapter.go
persist/adapter_filtered.go
persist/file-adapter/adapter.go
persist/file-adapter/adapter_filtered.go
persist/file-adapter/adapter_mock.go
persist/watcher_ex.go
rbac/default-role-manager/role_manager.go
rbac/default-role-manager/role_manager_test.go
rbac_api.go
rbac_api_test.go
rbac_api_with_domains_test.go
util/builtin_operators.go
watcher_ex_test.go

fix: update module to v3

---

management_api_test.go
model/policy.go
util/util.go

Signed-off-by: Cheng JIANG <jiang.cheng@vip.163.com>
close: #517

fix: duplicated policies inside rules to add

---

config/config_test.go
enforcer.go
enforcer_cached_b_test.go
enforcer_cached_test.go
enforcer_synced.go
enforcer_test.go
filter_test.go
management_api_test.go
managerment_api_b_test.go
model_b_test.go
model_test.go
rbac/default-role-manager/role_manager_test.go
rbac_api.go
rbac_api_test.go
rbac_api_with_domains_test.go
role_manager_b_test.go
util/util.go
watcher_ex_test.go
watcher_test.go

I will add golangci-lint to Casbin after merge.

test: fix golangci-lint error

---

rbac_api_with_domains_test.go

test: fix rbac_api_with_domains_test lint error

---

.github/workflows/default.yml
.travis.yml
Makefile

chore: add lint and benchmark to GitHub Actions

---

effect/default_effector.go
effect/default_effector_stream.go
effect/effector.go
effect/effector_stream.go
enforcer.go
enforcer_interface.go
enforcer_synced.go
enforcer_synced_test.go
enforcer_test.go
rbac_api_test.go

Signed-off-by: Cheng JIANG <jiang.cheng@vip.163.com>

feat: make enforcer.ClearPolicy different with Model.ClearPolicy

---

enforcer.go
enforcer_interface.go
enforcer_synced.go

feat: Autoloading in cachedenforcer

---

enforcer_test.go
error_test.go
management_api_test.go
rbac_api_test.go
rbac_api_with_domains_test.go

test: remove print test data

---

enforcer.go
internal_api.go
persist/dispatcher.go

feat: Distributed plugin Dispatcher

---

management_api.go

Signed-off-by: Andy Xia <118010339@link.cuhk.edu.cn>

fix: spelling error in comment of management_api.go

---

effect/default_effector.go

feat: add a rule of effect "Allow-override"

---

enforcer.go
enforcer_interface.go
model/model.go
model/policy.go
persist/adapter.go
persist/adapter_filtered.go
persist/file-adapter/adapter.go
persist/file-adapter/adapter_filtered.go
persist/file-adapter/adapter_mock.go
persist/watcher_ex.go
rbac_api.go
rbac_api_with_domains.go
watcher_ex_test.go

feat: add mutex to model

---

enforcer.go
enforcer_cached.go
internal_api.go
util/util.go

fix: https://github.com/casbin/casbin/issues/581

fix: Improve logger for management api

---

enforcer_interface.go
rbac_api.go
rbac_api_synced.go
rbac_api_test.go

Fix: https://github.com/casbin/casbin/issues/598

feat: Add Domain for some func

---

enforcer.go
model/assertion.go
model/policy.go

Signed-off-by: 00LT00 <lightning@zerokirin.online>
Fix: https://github.com/casbin/casbin/issues/614

fix: wrap the log printing in buildRoleLinks()

---

management_api.go

Signed-off-by: 00LT00 <lightning@zerokirin.online>

style: update parameter names

---

enforcer_interface.go

(old) Issues: #621 
(new) Fix: https://github.com/casbin/casbin/issues/621

fix: remove private methods from IEnforcer

---

enforcer.go
util/util.go
util/util_test.go

Fix: https://github.com/casbin/casbin/issues/619

fix: multiple eval() in matcher

---

enforcer.go
enforcer_synced.go
log/default_logger.go
log/log_util.go
log/log_util_test.go
log/logger.go
model/assertion.go
model/model.go
model/policy.go
rbac/default-role-manager/role_manager.go

Fix: https://github.com/casbin/casbin/issues/234
Improve the logger function.

feat: Improve logger

---

enforcer.go
model/model.go

feat: enable initialize logger with enforcer.

feat: enable initialize logger with enforcer

---

management_api.go
management_api_test.go

feat: Rename role

---

internal_api.go
persist/dispatcher.go

The affected policy is a meaningless in distributed system, I remove this.

fix: remove effects from dispatcher

---

.github/workflows/default.yml
Makefile

ci: upgrade golangci-lint and fixed semantic-release version

---

enforcer_distributed.go
enforcer_interface.go

fix: add persist to distributed enforcer

---

enforcer_distributed.go

fix: checks has policy

---

enforcer.go

fix: add autoNotifyDispatcher to initialize

---

enforcer_cached.go

Checked `CachedEnforcer`, seemed like it is supposed to be thread-safe since there is a mutex, but it isn't.
That should be now fixed.

fix: Make CachedEnforcer actually thread-safe

---

model/function.go
model/model_test.go
model_test.go
persist/dispatcher.go
rbac_api_synced.go
util/builtin_operators.go
util/builtin_operators_test.go

add new feature
Fix: https://github.com/casbin/casbin/issues/673

feat: add Extracting variables from paths(#673)

---

examples/keyget2_model.conf
examples/keyget_model.conf

add keyget_model.conf and keyget2_model.conf
keymatch_policy.csv and keymatch2_policy.csv are reused

docs: add examples for #675

---

enforcer.go
enforcer_distributed.go
enforcer_interface.go

fix: move set dispatcher function to distributed enforcer

---

enforcer_distributed.go
model/policy.go

A necessary thing that Model provides a set of methods that return the effected rules during update, the effected rules can be persist to file/db and more.

fix: add a set of methods to model that return the effected rules during update

---

internal_api.go
management_api.go
management_api_test.go
model/policy.go
persist/dispatcher.go
persist/file-adapter/adapter.go
persist/file-adapter/adapter_mock.go
persist/update_adapter.go
persist/watcher_update.go

Signed-off-by: RobotHuang <1183598761@qq.com>
fix: #690

feat: implement atomic UpdatePolicies() API

---

enforcer.go
enforcer_test.go

feat: Add BatchEnforce() API

---

rbac/default-role-manager/role_manager.go
rbac/default-role-manager/role_manager_test.go
rbac_api_test.go
util/util.go

fix: HasLink() couldn't get a correct result when RoleManager has MatchingFunc

---

enforcer_interface.go

fix: add update methods to enforcer interface

---

enforcer_distributed.go
enforcer_interface.go

- rename `AddPolicySelf` to `AddPoliciesSelf`
- rename `RemovePolicySelf` to `RemovePoliciesSelf`
- add `UpdatePoliciesSelf` methods to DistributedEnforcer

fix: improve the DistributedEnforcer

---

enforcer.go

fix: support forward the ClearPolicy to dispatcher

---

enforcer.go
enforcer_test.go
examples/priority_model_explicit.conf
examples/priority_policy_explicit.csv
internal_api.go
model/model.go
model/policy.go
rbac/default-role-manager/role_manager_test.go
util/util.go

Fix: #550 
method `UpdatePolicy` not support priority yet

feat: add priority support(#550)

---

rbac/default-role-manager/role_manager.go

fix: remove default role manager domain map

---

rbac/default-role-manager/role_manager.go

fix: HasLink wrong

---

enforcer.go

fix: enforcer action changed after calling `LoadPolicy`(#748)

---

frontend.go
frontend_test.go
model/model.go
rbac/default-role-manager/role_manager.go

fix: CasbinJsGetPermissionForUser incompatible with casbin-js

---

effector/default_effector.go
effector/effector.go
enforcer.go
enforcer_interface.go

Fix: https://github.com/casbin/casbin/issues/752

feat: Improve the Effector API, add enforce() short circuit to improve performance

---

enforcer.go
enforcer_distributed.go
enforcer_interface.go
enforcer_synced.go
internal_api.go
management_api.go
persist/dispatcher.go
persist/file-adapter/adapter.go
persist/update_adapter.go
rbac/default-role-manager/role_manager.go

Fix: https://github.com/casbin/casbin/issues/728
Fix: https://github.com/casbin/casbin/issues/731

feat: add updatefilteredpolicies

---

effector/default_effector.go

Fix: https://github.com/casbin/casbin/issues/763

fix: Set hit rule to first matched allow rule for allow-and-deny effect.

---

rbac_api.go

fix: GetPermissionsForUesr retrieves empty policy

---

rbac_api_with_domains.go

feat: add new rbac api

---

rbac/default-role-manager/role_manager.go

fix: improve logic and fix error for role manager

---

enforcer.go

fix: LoadPolicy clear model after failed

---

rbac_api.go

fix: GetPermissionsForUser panics on empty list of domains

---

rbac_api_with_domains.go

Signed-off-by: tangyang9464 tangyang9464@163.com
fix #814

fix: remove index in DeleteDomains method

---

enforcer.go
model/assertion.go
model/model.go
model/model_test.go
util/util.go

fix: fix the dirty data caused by LoadPolicy

---

enforcer.go
model/assertion.go
model/model.go
model/model_test.go
model_test.go
util/util.go

Fix: https://github.com/casbin/casbin/issues/820
Revert: https://github.com/casbin/casbin/pull/819

fix: initRmMap overriding custom RoleManagers

---

enforcer.go
enforcer_test.go
model/assertion.go
model/model.go

fix: lost model data if LoadPolicy failed

---

filter_test.go
persist/file-adapter/adapter_filtered.go

fix: filter not support mutiple ptype

---

effector/default_effector.go
enforcer.go
enforcer_test.go
examples/subject_priority_model.conf
examples/subject_priority_model_with_domain.conf
examples/subject_priority_policy.csv
examples/subject_priority_policy_with_domain.csv
model/model.go

Fix: #831
@hsluoyz @closetool plz review
@merajsahebdar plz just change ``priority(p.eft) || deny`` -> ``subjectPriority(p.eft) || deny``  and test your case.

feat: add prioritizing based on role and user hierarchy

---

internal_api.go
persist/watcher_ex.go
persist/watcher_update.go
watcher_ex_test.go

Fix: https://github.com/casbin/redis-watcher/issues/7
Added batch update methods to watcher interface to complete the implementation of redis watcher for https://github.com/casbin/redis-watcher/issues/7

feat: Added batch update watcher methods

---

model/policy.go

Adjust function RemoveFilteredPolicy ,I think it will remove Policy more efficiently in this way.
Signed-off-by: Edmond <edomondja@gmail.com>

perf: Adjust function RemoveFilteredPolicy

---

examples/subject_priority_policy.csv

Signed-off-by: Edmond <edomondja@gmail.com>

fix: Add data at subject_priority_policy.csv

---

enforcer.go
enforcer_test.go
examples/multiple_policy_definitions_model.conf
examples/multiple_policy_definitions_policy.csv
util/util.go

feat: multiple request, policy, effect, matcher type support

---

model/assertion.go
model/policy.go
model_test.go
rbac/default-role-manager/role_manager.go
rbac/default-role-manager/role_manager_test.go
rbac/role_manager.go
role_manager_b_test.go

fix: role inheritance fault

---

enforcer_test.go
examples/rbac_model_matcher_using_in_op_bracket.conf
model/model.go

feat: support bracket with in operator

---

enforcer.go
model/assertion.go
model_test.go
rbac/default-role-manager/role_manager_test.go

fix: make LoadPolicy seamless replacement policies

---

rbac_api_with_domains.go
rbac_api_with_domains_test.go

fix: GetPermissionsForUserInDomain not work

---

model/model.go
rbac/default-role-manager/role_manager.go
rbac_api_with_domains_test.go

fix: RoleManager match cache not concurrent

---

enforcer.go

Signed-off-by: 2448974318@qq.com
fix: #889

fix: Set the correct value for logExplains

---

enforcer.go
enforcer_test.go

fix: EnforceContext members private

---

model/policy.go

Signed-off-by: tangyang9464 tangyang9464@163.com
fix: #895

fix: model AddPolicy method can't set PolicyMap correctly

---

enforcer_cached.go

Fix: https://github.com/casbin/casbin/issues/924

feat: add CacheableParam interface

---

enforcer_cached.go

Fix: https://github.com/casbin/casbin/pull/925#issuecomment-991002012

fix: cached enforcer lint

---

rbac/default-role-manager/role_manager.go
rbac/default-role-manager/role_manager_test.go

Fix: https://github.com/casbin/casbin/issues/929
Refer to: https://github.com/casbin/casbin/issues/929#issuecomment-992190046

fix: multi-level inheritance with different domains

---

effector/default_effector.go

Signed-off-by: Jon Lee <techlee@qq.com>

perf: Optimize DefaultEffector to improve performance

---

frontend.go
frontend_test.go
model/model.go

FIx: https://github.com/casbin/casbin/issues/926

fix: CasbinJsGetPermissionForUser ignore p_eft and test

---

effector/default_effector.go

Signed-off-by: Jon Lee <techlee@qq.com>

fix: Not set hit rule when matched allow rule for rbac_with_deny_policy

---

enforcer_synced.go
management_api.go
management_api_test.go

Add Batch operations for `UpdateGroupingPolicy` and `UpdateNamedGroupingPolicy`.

feat: add batch methods for update grouping policies

---

enforcer_interface.go

Fix: https://github.com/casbin/casbin/issues/964

feat: added update grouping policies update methods to IEnforcer

---

enforcer_synced.go

fix: wrong locks with `BuildRoleLinks` and `SetWatcher`

---

management_api.go
management_api_test.go

Fix: https://github.com/casbin/casbin/issues/1007

feat: support GetFilteredNamedPolicyWithMatcher

---

persist/adapter.go
persist/persist_test.go

fix: #1011 
Signed-off-by: Andreas Bichinger <andreas.bichinger@gmail.com>

fix: handle duplicate adapter entries

---

rbac/default-role-manager/role_manager.go
rbac/default-role-manager/role_manager_test.go

Fix: https://github.com/casbin/casbin/issues/1033

fix: remove duplicate element when getRoles

---

rbac/default-role-manager/role_manager.go
rbac/default-role-manager/role_manager_test.go

fix: #1037 
Signed-off-by: Andreas Bichinger <andreas.bichinger@gmail.com>

fix(RoleManager): max hierarchy level

---

examples/priority_model_explicit_customized.conf
examples/priority_policy_explicit_customized.csv
rbac_api_test.go

fix https://github.com/casbin/casbin/issues/1015#issuecomment-1171915149

fix: add tests for SetFieldIndex&GetFieldIndex

---

.github/workflows/default.yml

ci: update the CI's golang versions

---

enforcer.go

feat: support GetNamedRoleManager & SetNamedRoleManager

---

enforcer_synced.go

fix #1076 
fix https://github.com/casbin/casbin/issues/1062#issuecomment-1197846067

fix: add GetLock for SyncedEnforcer

---

rbac_api.go
rbac_api_test.go

fix https://github.com/casbin/casbin/issues/1053#issuecomment-1187538374

fix: GetImplicitPermissionsForUser doesn't support multiple domains for consistency

---

enforcer_distributed.go
enforcer_interface.go
model/policy.go

chore: rename `effected` to `affected`

---

enforcer_interface.go
internal_api.go
management_api.go
persist/watcher_ex.go
watcher_ex_test.go
watcher_test.go
watcher_update_test.go

fix https://github.com/casbin/casbin/issues/1092
part of: https://github.com/casbin/casbin/issues/999

feat: add management api for WatcherEx

---

enforcer_interface.go
management_api.go

fix: typo of SelfSelfRemovePolicies

---

internal_api.go
persist/file-adapter/adapter.go
persist/update_adapter.go
persist/watcher_update.go

feat: add missing params in WatcherUpdatable interface

---

persist/adapter.go
persist/file-adapter/adapter.go
persist/file-adapter/adapter_filtered.go
persist/file-adapter/adapter_mock.go
persist/persist_test.go

fix https://github.com/casbin/casbin/issues/1083#issuecomment-1221529782

feat: return error in LoadPolicyArray and LoadPolicyLine

---

enforcer_synced.go

fix: refactor the LoadPolicy in SyncedEnforcer, reduce the lock range

---

rbac/role_manager.go

feat: Add RoleManagerWithContext interface for handling request timeouts

---

README.md

docs: updated broken links in README

---

CONTRIBUTING.md
README.md

Updated broken link and fixed styling.

docs: updated link

---

enforcer.go
util/builtin_operators.go

Trying to provide a solution for issue https://github.com/casbin/casbin/issues/1028 
All tests pass, but I'm not quite sure if every edge case is covered
Fix: https://github.com/casbin/casbin/issues/1028

feat: caching the govaluate expressions

---

util/util.go

Fix: https://github.com/casbin/casbin/issues/1183
https://github.com/casbin/casbin/issues/1183#issuecomment-1411301786

fix: SyncLRUCache Get

---

enforcer.go

Fix: https://github.com/casbin/casbin/issues/1181
https://github.com/casbin/casbin/issues/1181#issuecomment-1415122920

fix: LoadPolicy() does not reflect the latest results

---

rbac_api_with_domains.go
rbac_api_with_domains_test.go

Fix: https://github.com/casbin/casbin/issues/1189

feat: add GetAllRolesByDomain() API

---

enforcer_synced.go
enforcer_synced_test.go
util/util.go

fix: https://github.com/casbin/casbin/issues/1193

feat: fix locks in SyncedEnforcer Self* management API

---

persist/string-adapter/adapter.go
persist/string-adapter/adapter_test.go

Hi @hsluoyz  @qiangmzsx 
This PR is to merge [string-adapter](https://github.com/qiangmzsx/string-adapter) into casbin main  library.
All codes are copy from string-adapter and all unit test cases have passed. thank you. @qiangmzsx.

feat: merge string-adapter into casbin main library

---

rbac_api_synced.go

fix: https://github.com/casbin/casbin/issues/1208

fix: Data race in GetImplicitPermissionsForUser

---

enforcer_cached.go
enforcer_cached_synced.go
enforcer_cached_synced_test.go
persist/cache/cache_sync.go

Fix: https://github.com/casbin/casbin/issues/1214
I tried to add a sync cache and then add SyncedCachedEnforcer.

feat: add sync cache and synced cached enforcer

---

enforcer.go
enforcer_test.go
examples/keymatch_with_rbac_in_domain.conf
examples/keymatch_with_rbac_in_domain.csv

fix: fix keymatch with rbac in domain

---

.github/workflows/default.yml

fix: update the CI's golang versions

---

.github/workflows/staticcheck.yaml
enforcer.go
enforcer_synced_test.go
errors/rbac_errors.go
internal_api.go
rbac/default-role-manager/role_manager.go
rbac_api.go
rbac_api_test.go
util/builtin_operators.go
util/builtin_operators_test.go

* ci: include staticcheck Github action and fix errors

fix: include staticcheck Github action and fix errors

---

.github/workflows/PerformancePR.yml
.github/workflows/PerformancePush.yml

alert threshold from 150% to 110%

ci: change CI benchmark alert threshold

---

enforcer.go
go.mod
go.sum
model_test.go
util/util.go

fix: https://github.com/casbin/casbin/issues/1272

feat: support json request for ABAC

---

enforcer.go

fix: https://github.com/casbin/casbin/issues/1278

fix: Preprocess the access to the request object in the policy

---

model/policy.go

fix: different types of role definition panic

---

enforcer.go
examples/rbac_with_different_types_of_roles_model.conf
examples/rbac_with_different_types_of_roles_policy.csv
model_test.go

feat: fix different types of role definition wrong g function

---

persist/adapter.go
persist/adapter_context.go

fix: https://github.com/casbin/casbin/issues/1302

feat: add ContextAdapter interface to support context in adapters

---

enforcer.go

fix: https://github.com/casbin/casbin/issues/1312

fix: requestJsonReplace

---

README.md
enforcer.go
enforcer_interface.go
enforcer_synced.go
go.mod
go.sum
management_api.go
model/function.go
model_test.go
util/builtin_operators.go

feat: support map in ABAC

---

enforcer.go
go.mod
model_test.go
util/util.go

feat: support all types for JSON request in ABAC

---

enforcer_interface.go
rbac_api.go
rbac_api_synced.go
rbac_api_test.go

Fix: https://github.com/casbin/casbin/issues/1357
add error return for getUserPermissions

feat: return error in getUserPermissions() related APIs

---

enforcer.go
management_api.go
rbac_api.go
rbac_api_with_domains.go

Better error handling for: https://github.com/casbin/casbin/issues/1368
Fix: https://github.com/casbin/casbin/issues/1368

feat: add nil checks on RoleManager

---

rbac_api.go

feat: check error in GetNamedImplicitPermissionsForUser of GetFieldIndex

---

.github/workflows/PerformancePush.yml

- Upgrade actions' version
- Doubles benchtime, hope this can improve bench stability

feat: update PerformancePush config

---

rbac_api.go

feat: improve `GetNamedImplicitPermissionsForUser` performance

---

examples/rbac_with_multiple_policy_model.conf
examples/rbac_with_multiple_policy_policy.csv
rbac_api.go
rbac_api_synced.go
rbac_api_test.go

fix #1360 
This PR also fixes an unexpect logic change in #1405

feat: add named g support to `GetNamedImplicitPermissionsForUser`

---

go.mod
go.sum

Please see: https://github.com/casbin/govaluate/pull/9

feat: update casbin/govaluate package to fix nil pointer panic

---

.github/workflows/default.yml
Makefile

Similar to: https://github.com/casbin/casbin-go-cli/pull/3

feat: update release CI to fix error

---

model/model.go

This is a minor PR to fix a typo :)

feat: fix typo in model error message

---

enforcer.go
examples/rbac_with_domains_conditional_model.conf
examples/rbac_with_domains_conditional_policy.csv
rbac/default-role-manager/role_manager.go
rbac_api.go
rbac_api_test.go
rbac_api_with_domains.go
rbac_api_with_domains_test.go

Fix: https://github.com/casbin/casbin/issues/1336

feat: resolve issue where Enforcer could not retrieve roles from ConditionalRoleManager

---

enforcer.go
rbac/default-role-manager/role_manager.go

Fix: https://github.com/casbin/casbin/issues/1393

feat: fix issue that RBAC pattern doesn't work with conditions 

---

biba_test.go
examples/biba_model.conf

add Biba model and test case #1518

feat: add Biba model and test case

---

rbac_api.go
rbac_api_synced.go
rbac_api_test.go

Fix: https://github.com/casbin/casbin/issues/1529

feat: add GetImplicitObjectPatternsForUser API to get user's resource access patterns

---

enforcer_transactional.go
persist/transaction.go
transaction.go
transaction_buffer.go
transaction_commit.go
transaction_test.go

Fix: https://github.com/casbin/casbin/issues/1540

feat: add TransactionalEnforcer

---

transaction.go
transaction_commit.go
transaction_test.go

Fix: https://github.com/casbin/casbin/actions/runs/17785951217/job/50553595059?pr=1544

feat: resolve golangci-lint issues in transaction code

---

examples/pbac_model.conf
examples/pbac_policy.csv
pbac_test.go

Fix: https://github.com/casbin/casbin/issues/1543

feat: add PBAC  model support and test

---

enforcer_transactional.go
go.mod
go.sum
transaction.go
transaction_commit.go
transaction_conflict.go
transaction_test.go

Fix: https://github.com/casbin/casbin/issues/1540#issuecomment-3289683440

feat: enable concurrent transactions using optimistic locking, versioning and conflict detection
